# Generated by Django 5.2.12 on 2026-03-15 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id_alter_customuser_interface_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(blank=True, max_length=50)),
                ('item_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_downloader_failure', models.BooleanField(default=True)),
                ('notify_torrent_not_found', models.BooleanField(default=True)),
                ('notify_torrent_incomplete', models.BooleanField(default=True)),
                ('notify_sabnzbd_not_found', models.BooleanField(default=True)),
                ('notify_sabnzbd_incomplete', models.BooleanField(default=True)),
                ('notify_transfer_not_found', models.BooleanField(default=True)),
                ('notify_transfer_failure', models.BooleanField(default=True)),
                ('notify_sftp_failure', models.BooleanField(default=True)),
                ('notify_zip_failure', models.BooleanField(default=True)),
                ('notify_rar_failure', models.BooleanField(default=True)),
                ('notify_postprocess_failure', models.BooleanField(default=True)),
                ('notify_manual_intervention', models.BooleanField(default=True)),
                ('notify_item_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
