[supervisord]
nodaemon=true
logfile=/var/log/harpoon2/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:celery-worker]
command=celery -A harpoon2 worker -l debug
directory=/opt/harpoon2
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=10
stdout_logfile=/var/log/harpoon2/celery-worker.log
stderr_logfile=/var/log/harpoon2/celery-worker.log
environment=PYTHONUNBUFFERED=1

[program:celery-beat]
command=celery -A harpoon2 beat -l info --schedule=/data/celerybeat-schedule
directory=/opt/harpoon2
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=10
stdout_logfile=/var/log/harpoon2/celery-beat.log
stderr_logfile=/var/log/harpoon2/celery-beat.log
environment=PYTHONUNBUFFERED=1

[program:django]
command=python3 manage.py runserver 0.0.0.0:4277
directory=/opt/harpoon2
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=10
stdout_logfile=/var/log/harpoon2/django.log
stderr_logfile=/var/log/harpoon2/django.log
environment=PYTHONUNBUFFERED=1
