# Generated by Django 5.2.12 on 2026-03-10 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0009_alter_downloader_id_alter_downloadfolder_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('hash', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('size', models.BigIntegerField(default=0)),
                ('received', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='Created', max_length=50)),
                ('clientid', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('downloader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.downloader')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.manager')),
            ],
        ),
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='itemqueue.item')),
            ],
        ),
    ]
