# Generated by Django 5.2.12 on 2026-03-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemqueue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300)),
                ('remote_path', models.CharField(max_length=500)),
                ('local_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transferring', 'Transferring'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='itemqueue.item')),
            ],
        ),
    ]
