# Generated by Django 5.2.12 on 2026-03-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemqueue', '0002_filetransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
