# Generated by Django 5.2.12 on 2026-03-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemqueue', '0003_filetransfer_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='extraction_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='extraction_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='extraction_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='extraction_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
