# Generated by Django 5.2.12 on 2026-03-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemqueue', '0005_item_archived_item_archived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status', 'archived', '-modified'], name='itemqueue_i_status_7c5d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status', 'archived', '-archived_at'], name='itemqueue_i_status_8f3a1b_idx'),
        ),
    ]
