# Generated by Django 5.2.12 on 2026-03-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_auto_20201010_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloader',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='downloadfolder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='managertype',
            field=models.CharField(choices=[('Sonarr', 'Sonarr'), ('Radarr', 'Radarr'), ('Lidarr', 'Lidarr'), ('Readarr', 'Readarr'), ('Whisparr', 'Whisparr'), ('LazyLibrarian', 'LazyLibrarian'), ('Mylar', 'Mylar')], max_length=20),
        ),
    ]
