# Generated by Django 5.2.12 on 2026-03-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_alter_downloader_id_alter_downloadfolder_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seedbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(max_length=100)),
                ('auth_type', models.CharField(choices=[('password', 'Username/Password'), ('key', 'SSH Key')], default='password', max_length=10)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('ssh_key', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
