# Generated by Django 5.2.12 on 2026-03-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_seedbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedbox',
            name='base_download_folder',
            field=models.CharField(blank=True, help_text='Base path on seedbox for downloads (e.g., /home/user/downloads)', max_length=400, null=True),
        ),
    ]
