# Generated by Django 5.2.12 on 2026-03-11 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_seedbox_base_download_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloader',
            name='seedbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaders', to='entities.seedbox'),
        ),
    ]
