# Generated by Django 5.2.12 on 2026-03-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_downloader_seedbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadfolder',
            name='remote_folder_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
