# Generated by Django 5.2.12 on 2026-03-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0013_downloadfolder_remote_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='category',
            field=models.CharField(blank=True, help_text='Category to assign when not monitoring subdirectories', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='delete_source',
            field=models.BooleanField(default=True, help_text='Delete source .nzb/.torrent file after sending to downloader'),
        ),
        migrations.AddField(
            model_name='manager',
            name='duplicate_handling',
            field=models.CharField(choices=[('skip', 'Skip'), ('rename', 'Rename'), ('overwrite', 'Overwrite')], default='skip', help_text='How to handle duplicate files', max_length=10),
        ),
        migrations.AddField(
            model_name='manager',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable monitoring'),
        ),
        migrations.AddField(
            model_name='manager',
            name='monitor_directory',
            field=models.CharField(blank=True, help_text='Directory to monitor for .nzb and .torrent files', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='monitor_subdirectories',
            field=models.BooleanField(default=False, help_text='Monitor subdirectories for category detection'),
        ),
        migrations.AddField(
            model_name='manager',
            name='move_on_complete',
            field=models.BooleanField(default=True, help_text='Move files to destination (vs copy)'),
        ),
        migrations.AddField(
            model_name='manager',
            name='nzb_downloader',
            field=models.ForeignKey(blank=True, help_text='NZB client for .nzb files', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nzb_managers', to='entities.downloader'),
        ),
        migrations.AddField(
            model_name='manager',
            name='poll_interval',
            field=models.IntegerField(default=60, help_text='Seconds between directory scans'),
        ),
        migrations.AddField(
            model_name='manager',
            name='scan_on_startup',
            field=models.BooleanField(default=True, help_text='Process existing files on startup'),
        ),
        migrations.AddField(
            model_name='manager',
            name='temp_folder',
            field=models.CharField(blank=True, help_text='Temporary folder for incomplete downloads', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='torrent_downloader',
            field=models.ForeignKey(blank=True, help_text='Torrent client for .torrent files', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torrent_managers', to='entities.downloader'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='apikey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.downloadfolder'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='label',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
