# Generated by Django 5.2.12 on 2026-03-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_blackhole_manager_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='managertype',
            field=models.CharField(choices=[('Sonarr', 'Sonarr'), ('Radarr', 'Radarr'), ('Lidarr', 'Lidarr'), ('Readarr', 'Readarr'), ('Whisparr', 'Whisparr'), ('LazyLibrarian', 'LazyLibrarian'), ('Mylar', 'Mylar'), ('Blackhole', 'Blackhole')], max_length=20),
        ),
        migrations.CreateModel(
            name='CachedDownloaderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_downloads', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('downloader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_status', to='entities.downloader')),
            ],
            options={
                'verbose_name_plural': 'Cached downloader statuses',
            },
        ),
    ]
