# Generated by Django 5.2.12 on 2026-04-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_alter_manager_managertype_cacheddownloaderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloader',
            name='downloadertype',
            field=models.CharField(choices=[('RTorrent', 'RTorrent'), ('SABNzbd', 'SABNzbd'), ('AirDC++', 'AirDC++'), ('QBittorrent', 'QBittorrent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manager',
            name='apikey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='managertype',
            field=models.CharField(choices=[('Sonarr', 'Sonarr'), ('Radarr', 'Radarr'), ('Lidarr', 'Lidarr'), ('Readarr', 'Readarr'), ('Whisparr', 'Whisparr'), ('LazyLibrarian', 'LazyLibrarian'), ('Mylar3', 'Mylar3'), ('Bindery', 'Bindery'), ('Blackhole', 'Blackhole')], max_length=20),
        ),
    ]
